name: klutter
description: The Klutter Pub Plugin makes it possible to write a Flutter plugin for both Android and iOS using Kotlin only.
version: 0.1.0
publish_to: "none"
homepage: https://github.com/buijs-dev/klutter

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.19.5
  lints: ^1.0.0
  coverage: ^1.3.2

flutter: